[build]
  command = "git submodule update --init --recursive && hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.134.2"
  HUGO_ENV = "production"
  HUGO_EXTENDED = "true"

